### PR TITLE
fix: manual keyboard navigation

### LINKED ISSUE #2311: Manual sidebar acessibility
#2304 broke keyboard accessibility of the manual sidebar.

For example clicking on a chapter heading does not automatically open the details view for that chapter. The details view is automatically opened when a user navigates to a page inside of the chapter, but not when they are looking at the entrypoint for the chapter.

### PR DESCRIPTION
**Pull request by crowlKats**
Closes #2311

### CODE REVIEW

**Comment by lucacasonato** [comment]
Nice, this is working well. Please add the right aria labels to the triangles.

File: components/Icons.tsx [hunk 1]
```diff
@@ -190,10 +190,15 @@ export function ArrowRight(props: { class?: string }) {
...
 
-export function TriangleRight(props: { class?: string }) {
+export function TriangleRight(
+  props: { class?: string; tabindex?: number; onKeyDown?: string },
+) {
   return (
     <svg
       class={tw(props.class ?? "")}
+      tabindex={props?.tabindex}
+      // @ts-ignore onKeyDown does support strings
```
Comment (piscisaureus) [inline components/Icons.tsx:200]: Is it necessary to use a string though?

**Review by piscisaureus — APPROVED** [review]

File: components/Icons.tsx (hunk 1 above)
Comment (crowlKats) [reply components/Icons.tsx:200]: Yes, else if we'd use a normal callback, it would have to be an island

File: routes/manual.tsx [hunk 2]
```diff
@@ -244,55 +244,57 @@ function ToC({
...
+                    active ? "link bg-ultralight" : "hover:text-gray-500"
+                  } font-semibold` + (active ? " toc-active" : "")}
+                >
+                  <Icons.TriangleRight
+                    aria-label={`open section ${entry.name}`}
+                    onKeyDown="if (event.code === 'Space' || event.code === 'Enter') { this.parentElement.click(); event.preventDefault(); }"
+                    tabindex={0}
+                    class={"cursor-pointer" +
+                      (entry.children ? "" : " invisible")}
+                  />
```
Comment (lucacasonato) [inline routes/manual.tsx:264]: This can go entirely if you make `<summary>` a `display: list-item` instead of a `display: flex`.

File: routes/manual.tsx [hunk 3]
```diff
@@ -244,55 +244,57 @@ function ToC({
...
-              <label
-                htmlFor={slug}
-                class={tw`flex items-center gap-2 px-2.5 py-2 rounded-md block ${
-                  active ? "link bg-ultralight" : "hover:text-gray-500"
-                } font-semibold` + (active ? " toc-active" : "")}
+              <details
+                open={active}
+                class="rotate-svg"
+                // @ts-ignore onToggle does support strings
+                onToggle={`event.currentTarget.firstChild.firstChild.setAttribute("aria-label", (event.currentTarget.open ? "close" : "open") + " section ${entry.name}")`}
```
Comment (lucacasonato) [inline routes/manual.tsx:251]: not necessary if the triangle icon goes.

File: routes/manual.tsx (hunk 2 above)
Comment (crowlKats) [reply routes/manual.tsx:264]: the built-in triangle is worse, but ok...

**Review by kt3k — APPROVED** [review]
LGTM

**Comment by crowlKats** [comment]
removed details & summary as bug with chrome
